web/router.ex
defmodule SimilarfilmsPhoenix.Router do
  use SimilarfilmsPhoenix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", SimilarfilmsPhoenix do
    pipe_through :api

    resources "/movies", MovieApiController, only: [:index]
  end

  scope "/", SimilarfilmsPhoenix do
    pipe_through :browser # Use the default browser stack

    get "/", IndexController, :index
    resources "/movies", MovieController
    resources "/similar", SimilarController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", SimilarfilmsPhoenix do
  #   pipe_through :api
  # end
end

lib/similarfilms_phoenix/endpoint.ex
defmodule SimilarfilmsPhoenix.Endpoint do
  use Phoenix.Endpoint, otp_app: :similarfilms_phoenix

  socket "/socket", SimilarfilmsPhoenix.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :similarfilms_phoenix, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_similarfilms_phoenix_key",
    signing_salt: "sbRaUTE8"

  plug SimilarfilmsPhoenix.Router
end

lib/similarfilms_phoenix/repo.ex
defmodule SimilarfilmsPhoenix.Repo do
  use Ecto.Repo, otp_app: :similarfilms_phoenix
end

web/models/movie.ex
defmodule SimilarfilmsPhoenix.Movie do
  use SimilarfilmsPhoenix.Web, :model

  schema "movies" do
    field :movie_id, :integer
    field :title, :string
    field :rating, :decimal
    field :image_url, :string
    field :popularity, :decimal

    timestamps()
  end

  @doc """
  Sort movies by popularity so most popular is first
  """

  def limited(query, number) do
    from movie in query,
    limit: ^number
  end

  def sorted(query) do
    from movie in query,
    order_by: [desc: movie.popularity]
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:movie_id, :title, :rating, :image_url, :popularity])
    |> validate_required([:movie_id, :title, :rating, :image_url, :popularity])
  end
end

web/models/popular.ex
defmodule SimilarfilmsPhoenix.Popular do
  use SimilarfilmsPhoenix.Web, :model

  schema "popular_movies" do
    field :movie_id, :integer

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:movie_id])
    |> validate_required([:movie_id])
  end
end

web/controllers/index_controller.ex
defmodule SimilarfilmsPhoenix.IndexController do
  use SimilarfilmsPhoenix.Web, :controller

  def index(conn, _params) do
    data = get_popular()
    render conn, "index.html", results: data
  end
end

web/controllers/movie_api_controller.ex
defmodule SimilarfilmsPhoenix.MovieApiController do
  use SimilarfilmsPhoenix.Web, :controller

  alias SimilarfilmsPhoenix.Movie

  def index(conn, _params) do
    movies = Repo.all(Movie)
    render conn, "index.json", movies: movies
  end
end

web/controllers/movie_controller.ex
defmodule SimilarfilmsPhoenix.MovieController do
  use SimilarfilmsPhoenix.Web, :controller

  alias SimilarfilmsPhoenix.Movie

  def index(conn, _params) do
    movies = Repo.all(Movie)
    render(conn, "index.html", movies: movies)
  end

  def new(conn, _params) do
    changeset = Movie.changeset(%Movie{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"movie" => movie_params}) do
    changeset = Movie.changeset(%Movie{}, movie_params)

    case Repo.insert(changeset) do
      {:ok, _movie} ->
        conn
        |> put_flash(:info, "Movie created successfully.")
        |> redirect(to: movie_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    movie = Repo.get!(Movie, id)
    render(conn, "show.html", movie: movie)
  end

  def edit(conn, %{"id" => id}) do
    movie = Repo.get!(Movie, id)
    changeset = Movie.changeset(movie)
    render(conn, "edit.html", movie: movie, changeset: changeset)
  end

  def update(conn, %{"id" => id, "movie" => movie_params}) do
    movie = Repo.get!(Movie, id)
    changeset = Movie.changeset(movie, movie_params)

    case Repo.update(changeset) do
      {:ok, movie} ->
        conn
        |> put_flash(:info, "Movie updated successfully.")
        |> redirect(to: movie_path(conn, :show, movie))
      {:error, changeset} ->
        render(conn, "edit.html", movie: movie, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    movie = Repo.get!(Movie, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(movie)

    conn
    |> put_flash(:info, "Movie deleted successfully.")
    |> redirect(to: movie_path(conn, :index))
  end
end

web/controllers/similar_controller.ex
defmodule SimilarfilmsPhoenix.SimilarController do
  use SimilarfilmsPhoenix.Web, :controller

  def index(conn, _params) do
    data = get_popular
    render conn, "index.html", results: data
  end

  def show(conn, %{"id" => movie_id}) do
    data = get_similar(movie_id)
    render conn, "show.html", results: data
  end
end

web/views/error_view.ex
defmodule SimilarfilmsPhoenix.ErrorView do
  use SimilarfilmsPhoenix.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/index_view.ex
defmodule SimilarfilmsPhoenix.IndexView do
  use SimilarfilmsPhoenix.Web, :view
end

web/views/layout_view.ex
defmodule SimilarfilmsPhoenix.LayoutView do
  use SimilarfilmsPhoenix.Web, :view
end

web/views/movie_api_view.ex
defmodule SimilarfilmsPhoenix.MovieApiView do
  use SimilarfilmsPhoenix.Web, :view

  def render("index.json", %{movies: movies}) do
    %{
      movies: Enum.map(movies, &movie_json/1)
    }
  end

  def movie_json(movie) do
    %{
      title: movie.title,
      image: movie.image_url,
      rating: movie.rating,
      popularity: movie.popularity
    }
  end
end

web/views/movie_view.ex
defmodule SimilarfilmsPhoenix.MovieView do
  use SimilarfilmsPhoenix.Web, :view
end

web/views/shared_partials_view.ex
defmodule SimilarfilmsPhoenix.SharedPartialsView do
  use SimilarfilmsPhoenix.Web, :view
end

web/views/similar_view.ex
defmodule SimilarfilmsPhoenix.SimilarView do
  use SimilarfilmsPhoenix.Web, :view
end

web/templates/index/index.html.eex
<%= render SimilarfilmsPhoenix.SharedPartialsView, "title.html", title: "Popular" %>
<div class="container group">
  <%= render SimilarfilmsPhoenix.SharedPartialsView, "results.html", conn: @conn, results: @results %>
</div>


<!-- <script type="text/javascript" src="/assets/js/localforage/dist/localforage.js"></script>
<script type="text/javascript" src="/assets/js/app.pack.js"></script> -->

web/templates/layout/app.html.eex
<!DOCTYPE html>

<html>
  <head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <svg display="none" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="80" height="32" viewBox="0 0 80 32">
      <defs>
        <g id="icon-heart">
          <path class="path1" d="M32 11.192c0 2.699-1.163 5.126-3.015 6.808h0.015l-10 10c-1 1-2 2-3 2s-2-1-3-2l-9.985-10c-1.852-1.682-3.015-4.109-3.015-6.808 0-5.077 4.116-9.192 9.192-9.192 2.699 0 5.126 1.163 6.808 3.015 1.682-1.852 4.109-3.015 6.808-3.015 5.077 0 9.192 4.116 9.192 9.192z"></path>
        </g>
      </defs>
    </svg>

    <nav class="navigation">
      <ul class="connected-wrapper">
        <li class="connected-wrapper__item connected-wrapper__item--is-active">
          <a href="<%= index_path @conn, :index %>">Home</a>
        </li>
        <li class="connected-wrapper__item">
          <a href="{{url_for('mine')}}">Mine</a>
        </li>
      </ul>
    </nav>
    <div class="search-field">
      <form class="search-field__form" method="post" action="/search">
        <label class="visually-hidden" for="Search-Field__Search-Box">Search for a film</label>
        <input type="text" id="Search-Field__Search-Box" name="search" placeholder="search film" class="search-field__text">
        <input type="submit" class="search-field__submit" value="Find Movie">
      </form>
    </div>

    <main>
      <%= render @view_module, @view_template, assigns %>
    </main>
 <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/movie/edit.html.eex
<h2>Edit movie</h2>

<%= render "form.html", changeset: @changeset,
                        action: movie_path(@conn, :update, @movie) %>

<%= link "Back", to: movie_path(@conn, :index) %>

web/templates/movie/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :movie_id, class: "control-label" %>
    <%= number_input f, :movie_id, class: "form-control" %>
    <%= error_tag f, :movie_id %>
  </div>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :rating, class: "control-label" %>
    <%= number_input f, :rating, step: "any", class: "form-control" %>
    <%= error_tag f, :rating %>
  </div>

  <div class="form-group">
    <%= label f, :image_url, class: "control-label" %>
    <%= text_input f, :image_url, class: "form-control" %>
    <%= error_tag f, :image_url %>
  </div>

  <div class="form-group">
    <%= label f, :popularity, class: "control-label" %>
    <%= number_input f, :popularity, step: "any", class: "form-control" %>
    <%= error_tag f, :popularity %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/movie/index.html.eex
<h2>Listing movies</h2>

<table class="table">
  <thead>
    <tr>
      <th>Movie</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Image url</th>
      <th>Popularity</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for movie <- @movies do %>
    <tr>
      <td><%= movie.movie_id %></td>
      <td><%= movie.title %></td>
      <td><%= movie.rating %></td>
      <td><%= movie.image_url %></td>
      <td><%= movie.popularity %></td>

      <td class="text-right">
        <%= link "Show", to: movie_path(@conn, :show, movie), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: movie_path(@conn, :edit, movie), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: movie_path(@conn, :delete, movie), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New movie", to: movie_path(@conn, :new) %>

web/templates/movie/new.html.eex
<h2>New movie</h2>

<%= render "form.html", changeset: @changeset,
                        action: movie_path(@conn, :create) %>

<%= link "Back", to: movie_path(@conn, :index) %>

web/templates/movie/show.html.eex
<h2>Show movie</h2>

<ul>

  <li>
    <strong>Movie:</strong>
    <%= @movie.movie_id %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @movie.title %>
  </li>

  <li>
    <strong>Rating:</strong>
    <%= @movie.rating %>
  </li>

  <li>
    <strong>Image url:</strong>
    <%= @movie.image_url %>
  </li>

  <li>
    <strong>Popularity:</strong>
    <%= @movie.popularity %>
  </li>

</ul>

<%= link "Edit", to: movie_path(@conn, :edit, @movie) %>
<%= link "Back", to: movie_path(@conn, :index) %>

web/templates/shared_partials/results.html.eex
<%= if length(@results) < 1 do %>
  <%= render SimilarfilmsPhoenix.SharedPartialsView, "title.html", title: "No results" %>
<% end %>
<%= for result <- @results do %>
  <div class="movie-result">
    <div class="movie-result__tweet">
      <a href="http://twitter.com/home/?status=I'm watching <%= result["title"] %> because of http://similarfilms.com">Tweet</a>
    </div>
    
    <a href="<%= similar_path @conn, :show, result["movie_id"] %>" class="movie-result__image-link">
      <img src="http://image.tmdb.org/t/p/w300/<%= result["image_url"] %>" alt="<%= result["title"] %>" class="movie-result__image">
    </a>
    <div class="title"><%= result["title"] %></div>
    <div class="movie-result__rating-group">
      <div class="movie-result__rating"><%= result["rating"] %></div>
      <div class="movie-result__favourite-button">
        <button class="movie-result__heart" data-film="<%= result["title"] %>" data-id="<%= result["movie_id"] %>" data-rating="<%= result["rating"] %>" data-image="<%= result["image_url"] %>">
          <svg viewBox="0 0 32 32">
            <use xlink:href="#icon-heart"></use>
          </svg>
        </button>
      </div>
    </div>
  </div>
<% end %>

web/templates/shared_partials/title.html.eex
<div class="page-title">
  <h1 class="page-title__heading"><%= @title %></h1>
</div>

web/templates/similar/index.html.eex
<div class="container group">
  <%= render SimilarfilmsPhoenix.SharedPartialsView, "results.html", conn: @conn, results: @results %>
</div>

web/templates/similar/show.html.eex
<div class="container group">
  <%= render SimilarfilmsPhoenix.SharedPartialsView, "results.html", conn: @conn, results: @results %>
</div>